### ISSUE TITLE
Build 16

### ISSUE THREAD

**Issue by perexg** [perexg/satip-axe#127]
Goals:
 - fix the upgrade-fw (remote github release files) - done in build 15 fix1

**Comment by perexg** [comment]
Fix the upgrade-fw (remote files).

**Comment by doraid131** [comment]
tvheadend dont recognize satip anymore with the update firmaware .....

**Comment by perexg** [comment]
Do cold boot (turn off, wait 30 seconds, turn on).

**Comment by estimadarocha** [comment]
@perexg i am confirming the behavior but i am almost 80% sure that it really happens.

I have one network "dvb-s" that uses 4 tuner's of satipaxe and gives me around 100 channels.

I have other networks "dvb-c" and "dvb-t" that have exactly same channels so channels with same name are merged together.

I put highter priority on satipaxe tuner's so that i am sure that subscribers will pick first all the channels from satipaxe until there's no more available tuners.

i restart tvheadend to make sure the clients subscribing will follow priority rules...and it happens... i see in few seconds a few channels being picked from satipaxe.... however and the bad behavior appears now slowly the subscriptions start to move from the satipaxe to other networks. I didn't yet realize if this is caused by own minisatip from satipaxe, own tvheadend, or something wrong on descrambling.

So i am adding a "iptv network" where the mux's will be http stream's from satipaxe and try to figure if same happens!

**Comment by perexg** [comment]
@estimadarocha : report this for tvheadend. It has nothing to do with minisatip/satip-axe.

**Comment by estimadarocha** [comment]
@perexg thanks for the quick answer!

**Comment by estimadarocha** [comment]
@perexg is there anyway to see error's already happening or do i have to kill minisatip and start it again with log enabled? 

Got it stucked on 2 of 4 tuner's, tuner 0 and 2 stop responding to http streaming requests!

![satipaxe](https://user-images.githubusercontent.com/17991728/47157045-537cdf80-d2e0-11e8-8a38-bbbea9b3b187.jpg)

**Comment by phaze75** [comment]
oscamd is missing.

**Comment by perexg** [comment]
Any multiple access to the transponder stream consts too much time, because the stream must be parser per one MPEG-TS packet and split to different clients:

https://github.com/perexg/minisatip/blob/axe8/src/stream.c#L990-L992

So, for the optimal performance, use only one client per tuner and do the stream splitting somewhere else (install minisatip proxy on a more powerful machine for example). The SH4 CPU on this hardware is really slow.

**Comment by estimadarocha** [comment]
@perexg so if i grab a complete mux pids=all its a single access, correct?

**Comment by meijkl** [comment]
Is it an option to include Midnight Commander and htop in build 16?

**Comment by perexg** [comment]
https://github.com/perexg/satip-axe/issues/155
